# Generated by Django 2.0.1 on 2018-02-05 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_url', models.IntegerField()),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('date_crawl', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_200', models.IntegerField(blank=True, null=True)),
                ('nb_301', models.IntegerField(blank=True, null=True)),
                ('nb_302', models.IntegerField(blank=True, null=True)),
                ('nb_404', models.IntegerField(blank=True, null=True)),
                ('nb_500', models.IntegerField(blank=True, null=True)),
                ('outlinks_avg', models.FloatField(blank=True, null=True)),
                ('inlinks_avg', models.FloatField(blank=True, null=True)),
                ('avg_words', models.FloatField(blank=True, null=True)),
                ('nb_follow', models.IntegerField(blank=True, null=True)),
                ('nb_nofollow', models.IntegerField(blank=True, null=True)),
                ('low_content', models.IntegerField(blank=True, null=True)),
                ('missing_title', models.IntegerField(blank=True, null=True)),
                ('too_short_title', models.IntegerField(blank=True, null=True)),
                ('too_long_title', models.IntegerField(blank=True, null=True)),
                ('perfect_title', models.IntegerField(blank=True, null=True)),
                ('missing_desc', models.IntegerField(blank=True, null=True)),
                ('too_short_desc', models.IntegerField(blank=True, null=True)),
                ('perfect_desc', models.IntegerField(blank=True, null=True)),
                ('too_long_desc', models.IntegerField(blank=True, null=True)),
                ('duplicate_title', models.IntegerField(blank=True, null=True)),
                ('duplicate_desc', models.IntegerField(blank=True, null=True)),
                ('indexable_url', models.IntegerField(blank=True, null=True)),
                ('nb_canonical', models.IntegerField(blank=True, null=True)),
                ('perfect_loadtime', models.IntegerField(blank=True, null=True)),
                ('medium_loadtime', models.IntegerField(blank=True, null=True)),
                ('slow_loadtime', models.IntegerField(blank=True, null=True)),
                ('words_150', models.IntegerField(blank=True, null=True)),
                ('words_150_300', models.IntegerField(blank=True, null=True)),
                ('words_300_500', models.IntegerField(blank=True, null=True)),
                ('words_500_800', models.IntegerField(blank=True, null=True)),
                ('words_800_1200', models.IntegerField(blank=True, null=True)),
                ('words_1200', models.IntegerField(blank=True, null=True)),
                ('crawl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_id', to='crawler.Crawl')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=True)),
                ('internal', models.BooleanField()),
                ('anchor', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('domain', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_project_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_kw', models.CharField(blank=True, max_length=200, null=True)),
                ('canonical', models.CharField(blank=True, max_length=500, null=True)),
                ('response_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('noindex_robot', models.BooleanField()),
                ('nofollow_robot', models.BooleanField()),
                ('in_sitemap', models.BooleanField()),
                ('nb_words', models.IntegerField()),
                ('html_content', models.TextField()),
                ('first_h1', models.CharField(blank=True, max_length=200, null=True)),
                ('crawl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_crawl', to='crawler.Crawl')),
            ],
        ),
        migrations.CreateModel(
            name='UrlStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlinks', models.IntegerField(blank=True, null=True)),
                ('inlinks', models.IntegerField(blank=True, null=True)),
                ('title_length', models.IntegerField(blank=True, null=True)),
                ('desc_length', models.IntegerField(blank=True, null=True)),
                ('depth_level', models.IntegerField(blank=True, null=True)),
                ('h1', models.IntegerField(blank=True, null=True)),
                ('h2', models.IntegerField(blank=True, null=True)),
                ('h3', models.IntegerField(blank=True, null=True)),
                ('h4', models.IntegerField(blank=True, null=True)),
                ('h5', models.IntegerField(blank=True, null=True)),
                ('h6', models.IntegerField(blank=True, null=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_url', to='crawler.UrlDetail')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_id', to='crawler.UrlDetail'),
        ),
        migrations.AddField(
            model_name='crawl',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='crawler.Project'),
        ),
    ]
