# Generated by Django 2.0.1 on 2018-02-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180205_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawl',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='globalstat',
            old_name='crawl_id',
            new_name='crawl',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='url_id',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='urldetail',
            old_name='crawl_id',
            new_name='crawl',
        ),
        migrations.RenameField(
            model_name='urlstat',
            old_name='url_id',
            new_name='url',
        ),
    ]
